# Based on https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - libffi-dev
      - libtinfo-dev
      - zlib1g-dev
      - pkg-config
      - libgc-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  ## Emacs 24.3
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get -f install
  - sudo apt-get install -qq emacs24 emacs24-el

  ## Emacs 24.4
  - wget http://ftpmirror.gnu.org/emacs/emacs-24.4.tar.xz
  - tar -xf emacs-24.4.tar.xz
  - cd emacs-24.4
  - ./configure --prefix=/usr/local/emacs-24.4 --with-xpm=no --with-gif=no
  - make
  - sudo make install
  - cd ..

  ## Emacs 25.3
  - wget http://ftpmirror.gnu.org/emacs/emacs-25.3.tar.xz
  - tar -xf emacs-25.3.tar.xz
  - cd emacs-25.3
  - ./configure --prefix=/usr/local/emacs-25.3 --with-xpm=no --with-gif=no
  - make
  - sudo make install
  - cd ..

# Install Idris
install:
  - pushd .
  - git clone https://github.com/idris-lang/Idris-dev.git /tmp/Idris-dev
  - cd /tmp/Idris-dev
  - stack --no-terminal --install-ghc install

before_script: true

script:
  - popd

  # emacs 24.3
  - make test
  - make clean

  # emacs 24.4
  - make test EMACS=/usr/local/emacs-24.4/bin/emacs
  - make clean

  # emacs 25.3
  - make test EMACS=/usr/local/emacs-25.3/bin/emacs
  - make clean
