language: haskell

before_install:
      ## Emacs 24.3
      - sudo add-apt-repository -y ppa:cassou/emacs
      - sudo apt-get update -qq
      - sudo apt-get -f install
      - sudo apt-get install -qq emacs24 emacs24-el

      ## Emacs 24.4
      - wget http://ftpmirror.gnu.org/emacs/emacs-24.4.tar.xz
      - tar -xf emacs-24.4.tar.xz
      - cd emacs-24.4
      - ./configure --prefix=/usr/local/emacs-24.4 --with-xpm=no --with-gif=no
      - make
      - sudo make install
      - cd ..

      ## Idris prereqs
      - sudo add-apt-repository --yes ppa:h-rayflood/llvm
      - sudo apt-get update -qq
      - sudo apt-get install -qq libgc-dev llvm-3.3
      - sudo apt-get install -qq libghc-unordered-containers-dev libghc-mtl-dev libghc-network-dev libghc-xml-dev libghc-transformers-dev libghc-text-dev libghc-utf8-string-dev libghc-vector-dev libghc-split-dev libghc-ansi-terminal-dev libghc-ansi-wl-pprint-dev
      # trifecta dependencies
      - sudo apt-get install -qq libghc-blaze-builder-dev libghc-blaze-html-dev libghc-bifunctors-dev libghc-hashable-dev libghc-semigroups-dev libghc-semigroupoids-dev libghc-parallel-dev libghc-comonad-dev libghc-terminfo-dev libghc-keys-dev
      # Haddock dependencies
      - sudo apt-get install hscolour
      # test dependency
      - sudo apt-get install -qq expect
      - cabal install alex

# Install Idris
install:
      - pushd .
      - git clone https://github.com/idris-lang/Idris-dev.git /tmp/Idris-dev
      - cd /tmp/Idris-dev
      - cabal install -f FFI -f LLVM --only-dependencies --enable-tests --max-backjumps=-1 --force-reinstalls
      - cabal configure -f FFI -f LLVM
      - cabal sdist
      - cd ..
      - tar -xf Idris-dev/dist/idris*.tar.gz
      - cd idris*
      - cabal configure -f FFI -f LLVM
      - cabal build
      - cabal copy

before_script: true

script:
      - popd

      # emacs 24.3
      - make getdeps
      - make build
      - make test
      - make clean

      # emacs 24.4
      - make getdeps EMACS=/usr/local/emacs-24.4/bin/emacs
      - make build EMACS=/usr/local/emacs-24.4/bin/emacs
      - make test EMACS=/usr/local/emacs-24.4/bin/emacs
      - make clean
